# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'pry'

describe 'LoginLogout' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @dropdown = Selenium::WebDriver::Support::Select

    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'loginLogout' do
    @driver.get('https://staging.motorama.com/')
    @driver.manage.window.maximize
    @driver.find_element(:css, '.account > a').click
    @driver.find_element(:id, 'session_person_email').send_keys('test_rus_01@hotmail.com')
    @driver.find_element(:id, 'session_person_password').send_keys('Tester123')
    @driver.find_element(:name, 'commit').click
    # @driver.find_element(:css, '#dropdown-account > .fal').click
    # element = @driver.find_element(:css, '#dropdown-account > .fal')
    # @driver.action.move_to(element).click_and_hold.perform

    
    
    @driver.find_element(:css, '#dropdown-account > .fal').click
    element = @driver.find_element(:link_text, 'Log Out')
    @driver.action.move_to(element).click.perform
    @driver.action.double_click(element).perform

    binding.pry

    element = @driver.find_element(:link_text, 'Log Out')
    @driver.action.move_to(element).click.perform
    @driver.action.double_click(element).perform

    @driver.find_element(:link_text, 'Orders')

    #######################
    dropdown_list = @driver.find_element(:css, '.dropdown-item:nth-child(6)')
    options = dropdown_list.find_elements(:link_text, "Log Out")
    options.each { |option| option.click if option.text == 'Log Out' }
    selected_option = options.map { |option| option.text if option.selected? }.join

    @driver.find_element(:link_text, 'Orders').click


    ######################
    element = @driver.find_element(:link_text, "Log Out")
    dropdown = Selenium::WebDriver::Support::Select.new(element)
    chan_text = element.text
    dropdown.select_by(:text, chan_text)
    dropdown.select_by(:link_text, "Log Out")
    expect(selected_option).to eql 'Log Out'


   

    selected_option = select_list.selected_options[0].text
    expect(selected_option).to eql 'Option 1'



    element = @driver.find_element(:xpath, "//a[contains(@href, '/account/logout')]")
    @driver.action.move_to(element).click.perform
    @driver.find_element(:css, '.dropdown-item:nth-child(6)').click
    @driver.find_element(:xpath, "//a[contains(@href, '/account/logout')]").click
    element = @driver.find_element(:css, '.dropdown-item:nth-child(6)')



    dropdown = @driver.find_element(id: 'dropdown')
    select_list = Selenium::WebDriver::Support::Select.new(dropdown)
    select_list.select_by(:text, 'Option 1')
  
    selected_option = select_list.selected_options[0].text
    expect(selected_option).to eql 'Option 1'

  end
end

