# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
require 'rspec'
describe 'LoginToNemo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  def accept_cookies (driver)
    testcon = driver.find_element(:css, '.accept-cookies-button')
    if (testcon.displayed?)
      testcon.click
    end
  rescue StandardError => e
     puts "Rescued: #{e.inspect}"
  end
  it 'loginToNemo' do
    @driver.get('https://brokers.leaseplan.co.uk/login.asp')
    @driver.manage.resize_to(550, 680)
    @driver.find_element(:id, 'txtuserNameWPQ1_DOCQ1').click
    @driver.find_element(:id, 'txtuserNameWPQ1_DOCQ1').send_keys('Damien.fortune@autorama.co.uk')
    @driver.find_element(:id, 'txtpassWordWPQ1_DOCQ1').click
    @driver.find_element(:id, 'txtpassWordWPQ1_DOCQ1').send_keys('Autotama1')
    @driver.find_element(:css, '.ap-login-action span').click
    @driver.find_element(:id, 'txtpassWordWPQ1_DOCQ1').click
    @driver.find_element(:id, 'txtpassWordWPQ1_DOCQ1').send_keys('Autorama1')
    @driver.find_element(:css, '.ap-login-action span').click
    accept_cookies(@driver)
    @driver.find_element(:link_text, 'NeMO').click
  end
end
