# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'.TM_RAILS_TEMPLATE_START_RUBY_EXPRf.check_box :attributeTM_RAILS_TEMPLATE_END_RUBY_EXPR
describe 'Nemo' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  def wait_for_window(self, timeout = 2)
    sleep(round(timeout / 1000))
    wh_now = @driver.window_handles
    wh_then = @vars['window_handles']
    wh_now.find { |window| window != wh_then.first}
  end
  it 'nemo' do
    @driver.get('https://brokers.leaseplan.co.uk/login.asp?urlRedirect=%2fdashboard.asp')
    @driver.manage.resize_to(1272, 340)
    @driver.find_element(:css, '.ap-login-action span').click
    @driver.find_element(:css, '.hamburger__label').click
    @driver.find_element(:id, 'wpq7_docq1_mainmenu___myfleetnetworkcommcentrecouk_documents_modules_menuitems_networkportal_nemo').click
    @vars['window_handles'] = @driver.window_handles
    @driver.find_element(:link_text, 'NeMO').click
    @vars['win7761'] = wait_for_window(2000)
    @vars['root'] = @driver.window_handle
    @driver.switch_to.window(@vars['win7761'])
    @driver.execute_script("window.scrollTo(0,213.3333282470703)")
    @driver.find_element(:id, 'j_id0:idform:j_id3:j_id103').click
    @driver.find_element(:link_text, 'ACCEPT').click
    @driver.find_element(:link_text, 'ACCEPT').click
    @driver.find_element(:link_text, 'ACCEPT').click
    @driver.find_element(:link_text, 'SELECT').click
    expect(@driver.find_element(:link_text, 'SELECTED').text).to eq('SELECTED')
    @driver.find_element(:id, 'j_id0:form:j_id5:Idfirstname').click
    @driver.find_element(:id, 'j_id0:form:j_id5:Idfirstname').send_keys('Liam')
    @driver.find_element(:name, 'j_id0:form:j_id5:j_id314').click
    @driver.find_element(:name, 'j_id0:form:j_id5:j_id314').send_keys('Meehan')
    @driver.find_element(:id, 'j_id0:form:j_id5:idDay').click
    @driver.find_element(:id, 'j_id0:form:j_id5:idDay').send_keys('17')
    @driver.find_element(:id, 'j_id0:form:j_id5:idMonth').click
    @driver.find_element(:id, 'j_id0:form:j_id5:idMonth').send_keys('02')
    @driver.find_element(:id, 'j_id0:form:j_id5:idYear').click
    @driver.find_element(:id, 'j_id0:form:j_id5:idYear').send_keys('1994')
    @driver.find_element(:id, 'j_id0:form:j_id5:idPostCode').click
    @driver.find_element(:id, 'j_id0:form:j_id5:idPostCode').send_keys('hp2 7bw')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode1').click
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode1').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode2').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode3').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode4').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode5').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idSortCode6').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode1').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode2').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode3').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode4').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode5').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode6').send_keys('1')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode7').send_keys('0')
    @driver.find_element(:id, 'j_id0:form:j_id5:idACode8').send_keys('1')
    element = @driver.find_element(:css, '.button')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '.button')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, '.button')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:css, '.button').click
    @driver.execute_script("window.scrollTo(0,1248)")
    @driver.find_element(:css, 'h2 > .textalign--center').click
    expect(@driver.find_element(:css, 'h2 > .textalign--center').text).to eq('We couldn’t find an existing customer.')
    @driver.find_element(:css, '.button:nth-child(2)').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id279SelectBoxItText').click
    element = @driver.find_element(:css, '.selectboxit-focus > .selectboxit-option-anchor')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'h3:nth-child(2)')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id272').click
    @driver.find_element(:css, '.walkme-custom-balloon-button-text').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id310SelectBoxItText').click
    element = @driver.find_element(:css, '#idPageConsumer\\3AidForm\\3Aj_id13\\3Aj_id310SelectBoxItOptions > .selectboxit-focus > .selectboxit-option-anchor')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '.checkbox-label')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id272').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id316SelectBoxItText').click
    element = @driver.find_element(:css, '.selectboxit-option-last:nth-child(7) > .selectboxit-option-anchor')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id318')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id272').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:checkbox1').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:checkbox1').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:0:InvokeRapidSearchButtonId0').click
    @driver.switch_to.frame(3)
    @driver.switch_to.frame(0)
    @driver.switch_to.frame(0)
    @driver.find_element(:css, 'a > div').click
    @driver.find_element(:css, 'tr:nth-child(13) div').click
    @driver.switch_to.default_content
    @driver.find_element(:id, 'Accept').click
    @driver.switch_to.default_content
    @driver.switch_to.default_content
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:0:idAddressMonth').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:0:idAddressMonth').send_keys('12')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:0:idAddressYear').send_keys('2018')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:0:idAddressYear').send_keys(:enter)
    @driver.find_element(:css, '.icon-plus-circle:nth-child(1)').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:postcode__c').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:postcode__c').send_keys('hp2 7de')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:InvokeRapidSearchButtonId0').click
    @driver.switch_to.frame(4)
    @driver.switch_to.frame(0)
    @driver.switch_to.frame(0)
    @driver.find_element(:css, 'a > div').click
    @driver.find_element(:css, 'tr:nth-child(3) div').click
    @driver.switch_to.default_content
    @driver.find_element(:id, 'Accept').click
    @driver.switch_to.default_content
    @driver.switch_to.default_content
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:fromAddressMonth').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:fromAddressMonth').send_keys('12')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id461:j_id462:j_id465:1:fromAddressyear').send_keys('2014')
    @driver.find_element(:css, '.address__c_to__c').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:j_id650').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:mainphone').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:mainphone').send_keys('02071234567')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idmobilephonenumber').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idmobilephonenumber').send_keys('071234567')
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idemail').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idemail').send_keys('lian.meehan@autorama.co.uk')
    @driver.find_element(:css, '.button:nth-child(2)').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idmobilephonenumber').click
    @driver.find_element(:id, 'idPageConsumer:idForm:j_id13:idmobilephonenumber').send_keys('07123456789')
    @driver.find_element(:css, '.button:nth-child(2)').click
    @driver.execute_script("window.scrollTo(0,435.3333435058594)")
    @driver.find_element(:link_text, 'AGREE').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id8:j_id332').click
    @driver.execute_script("window.scrollTo(0,5.333333492279053)")
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:selectSelectBoxItText').click
    element = @driver.find_element(:css, '.selectboxit-focus > .selectboxit-option-anchor')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:id, 'j_id0:idfrm:j_id4:selectSelectBoxItText')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:selectSelectBoxItContainer').click
    @driver.execute_script("window.scrollTo(0,508)")
    @driver.find_element(:name, 'j_id0:idfrm:j_id4:j_id246').click
    @driver.find_element(:name, 'j_id0:idfrm:j_id4:j_id246').send_keys('Senior Customer Credit Specialist')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:j_id253').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:j_id253').send_keys('Autorama UK Ltd')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:postcode__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:postcode__c').send_keys('HP2 7DE')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:InvokeRapidSearchButtonId0').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:InvokeRapidSearchButtonId0').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:InvokeRapidSearchButtonId0').click
    @driver.find_element(:css, 'html').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:postcode__c').send_keys('HP2 7DE')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:house_name__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:house_name__c').send_keys('Vanarama')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:street__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:street__c').send_keys('Marylands Avenue')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:town__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:town__c').send_keys('Hemel Hempstead')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:idPostCode').send_keys('hp2 5de')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:county__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:county__c').send_keys('Hertforshire')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:country__c').click
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:country__c').send_keys('United Kingdom')
    @driver.find_element(:id, 'j_id0:idfrm:j_id4:j_id332').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:j_id244SelectBoxItText').click
    element = @driver.find_element(:css, '.selectboxit-option-last > .selectboxit-option-anchor')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '.cp_agree_contacts__c_monthly_income__c')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:j_id237').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idMonthlyIncome').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idMonthlyIncome').send_keys('2000')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idHousing').send_keys('500')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idUtilities').send_keys('80')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idEmplrMonthly').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idEmplrMonthly').send_keys('0')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idTransport').send_keys('80')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idOther').send_keys('120')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idPhone').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idPhone').send_keys('35')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idInsurance').send_keys('40')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idCreditCards').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idCreditCards').send_keys('200')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idOtherLoan').send_keys('35')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idcarLoan').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idcarLoan').send_keys('0')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:idTotalOther').send_keys('200')
    @driver.find_element(:css, '.button--primary').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:iddisposalinc').click
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:iddisposalinc').send_keys('0')
    @driver.find_element(:id, 'idIncExpensePage:idForm:j_id6:iddisposalinc').click
    @driver.find_element(:css, '.button--primary').click
    @driver.find_element(:id, 'j_id0:frm:j_id2:j_id232').click
    @driver.find_element(:css, '.button--primary').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:Reason_ProposalSelectBoxItText').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:IdMainPanel').click
    element = @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description').send_keys('Ford Focus 1.8 S')
    element = @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:FINDAttachQuoteMain')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, '#IdPage\\3Aj_id1\\3Aj_id195\\3AIdPage\\3AIdForm\\3A actStatusId\\.start > #el_loading')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:FINDAttachQuoteMain').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id528').click
    @driver.switch_to.window(@vars['root'])
    expect(@driver.switch_to.alert.text).to eq('This session will expire in five minutes. To remain connected and to prevent possible data loss, please validate this window.')
    @driver.switch_to.window(@vars['win7761'])
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:description').send_keys('Renault CLIO HATCHBACK 0.9 TCE 90 GT Line 5dr')
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id527').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:costMonthlyRental').send_keys('250')
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:costCapitalCost').send_keys('11500')
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:FINDAttachQuoteMain').click
    @driver.find_element(:css, '.card-row:nth-child(3) > .tab-one-fifth:nth-child(5) .small').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:Idquotesbox8:4:j_id499').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
    @driver.find_element(:id, 'IdPage:j_id1:j_id195:IdPage:IdForm:wtable:0:j_id516:IdNextPreviousNEXT').click
  end
end
